# This rule is not used by the project identity-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to identity.lapacek-labs.org resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: identity-operator
    app.kubernetes.io/managed-by: kustomize
  name: identitysyncpolicy-viewer-role
rules:
- apiGroups:
  - identity.lapacek-labs.org
  resources:
  - identitysyncpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - identity.lapacek-labs.org
  resources:
  - identitysyncpolicies/status
  verbs:
  - get
