# This rule is not used by the project identity-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the identity.lapacek-labs.org.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: identity-operator
    app.kubernetes.io/managed-by: kustomize
  name: identitysyncpolicy-editor-role
rules:
- apiGroups:
  - identity.lapacek-labs.org
  resources:
  - identitysyncpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - identity.lapacek-labs.org
  resources:
  - identitysyncpolicies/status
  verbs:
  - get
